
[34m[1mwandb[39m[22m: logging graph, to disable use `wandb.watch(log_graph=False)`
Traceback (most recent call last):
  File "session-5/main.py", line 75, in <module>
    run_reconstruction(
  File "C:\Users\joanpg5\Documents\aidl-2023-winter-mlops\session-5\run_reconstruction.py", line 94, in run_reconstruction
    logger.log_reconstruction_training(
  File "C:\Users\joanpg5\Documents\aidl-2023-winter-mlops\session-5\wandb_TODO.py", line 51, in log_reconstruction_training
    wandb.log({"batch of reconstructed images": wandb.Image(np.array(reconstruction_grid))}, epoch)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\data_types\image.py", line 143, in __init__
    self._initialize_from_data(data_or_path, mode)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\data_types\image.py", line 272, in _initialize_from_data
    self.to_uint8(data), mode=mode or self.guess_mode(data)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\data_types\image.py", line 418, in guess_mode
    raise ValueError(
ValueError: Un-supported shape for image conversion [3, 482, 242]